### PR TITLE
feature: update models and migrations according to interface agreement

### PR DESCRIPTION
**Pull request by JuanJoseRomeroMontes**

### CODE REVIEW

**Comment by dajramirez** [comment]
latitude and longitude must be float numbers

image

**Comment by JuanJoseRomeroMontes** [comment]
> latitude and longitude must be float numbers
> 
> image

You're right, i've made a new commit to fix this.

**Comment by dajramirez** [comment]
Perfect!

**Review by dajramirez — APPROVED** [review]
Everything ok

**Pull request merged**
